#!/bin/sh

# Runs when a DM logs you into a graphical session

# Sets the background
setbg &

# For notifications
dunst &

# nm-applet
nm-applet --indicator &

# Starting compositor
picom -b

# Stop screen from going blank
xset s off
xset -dpms
xset s noblank

# Faster key repeat and delay
xset r rate 210 40

# Save your eyes
#redshift &
# redshift-gtk &
